apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - backup-cronjob.yaml
  - local-storage.yaml
  - media-storage.yaml
  - virtualservice.yaml
configMapGenerator:
  - name: sonarr-config-migration
    files:
      - migrate-config.sh
generatorOptions:
  disableNameSuffixHash: true
