serviceAccount:
  sonarr: {}
controllers:
  sonarr:
    serviceAccount:
      identifier: sonarr
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.15
        env:
          TZ: America/Los_Angeles
          PUID: "1000"
          PGID: "1000"
          DELUGE_URL: http://deluge.media.svc.cluster.local:8112
service:
  app:
    controller: sonarr
    ports:
      http:
        port: 8989
persistence:
  config:
    enabled: true
    storageClass: nfs-default
    size: 10Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
  media:
    enabled: true
    storageClass: nfs-default
    size: 500Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /tv
  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: deluge-downloads
    globalMounts:
      - path: /downloads
