controllers:
  sonarr:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.15@sha256:fbe67c25693dc5f3de220c5691f374576ae265df782c16918cc071b630490bd7
        env:
          TZ: America/Los_Angeles
          PUID: "1000"
          PGID: "1000"
          DELUGE_URL: http://deluge.media.svc.cluster.local:8112
service:
  app:
    controller: sonarr
    ports:
      http:
        port: 8989
persistence:
  config:
    enabled: true
    storageClass: nfs-default
    size: 10Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
  media:
    enabled: true
    storageClass: nfs-default
    size: 500Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /tv
  downloads:
    enabled: true
    storageClass: nfs-default
    size: 200Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /downloads

