apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: n8n-tailnet
  namespace: automation
  annotations:
    homelab.rst.io/public-funnel: "false"
spec:
  hosts:
    - n8n.stinkyboi.com
  gateways:
    - istio-system/tailnet-gateway
  http:
    - route:
        - destination:
            host: n8n.automation.svc.cluster.local
            port:
              number: 5678
