apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - user-namespace-sysctl.yaml
  - networkpolicy.yaml
  - virtualservice.yaml
  - cordium-bootstrap-application.yaml
