apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-auth
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: radarr-auth
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: /homelab/radarr/api-key
    - secretKey: deluge-api-key
      remoteRef:
        key: /homelab/radarr/deluge-api-key

