controllers:
  radarr:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: 5.27.5@sha256:af03fa6a993ee7efb65f6121ebd8c89de4a47aa1181cec03832e292a1446111f
        env:
          TZ: America/Los_Angeles
          PUID: "1000"
          PGID: "1000"
          DELUGE_URL: http://deluge.media.svc.cluster.local:8112
service:
  app:
    controller: radarr
    ports:
      http:
        port: 7878
persistence:
  config:
    enabled: true
    storageClass: nfs-default
    size: 10Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
  media:
    enabled: true
    storageClass: nfs-default
    size: 500Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /movies
  downloads:
    enabled: true
    storageClass: nfs-default
    size: 200Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /downloads

