apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-secrets
  namespace: affine
  annotations:
    homelab.stuhlmuller.dev/generated-secret-revision: "v1"
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: affine-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        REDIS_PASSWORD: "{{ .redis_password }}"
        AFFINE_PRIVATE_KEY: "{{ .private_key }}"
  data:
    - secretKey: postgres_password
      remoteRef:
        key: /homelab/affine/postgres-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: redis_password
      remoteRef:
        key: /homelab/affine/redis-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: private_key
      remoteRef:
        key: /homelab/affine/private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
