apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: affine
  namespace: collaboration
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: affine
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 3010
