apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-data
  namespace: collaboration
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/part-of: affine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-default
  resources:
    requests:
      storage: 50Gi
