apiVersion: v1
kind: ServiceAccount
metadata:
  name: affine
  namespace: affine
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/part-of: homelab-productivity
automountServiceAccountToken: false
