---
apiVersion: v1
kind: ConfigMap
metadata:
  name: octelium-public-cloudflared
  namespace: octelium-public
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: octelium-public
data:
  config.yaml: |
    no-autoupdate: true
    metrics: 0.0.0.0:2000
    protocol: quic
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 10s
      http2Origin: true
    ingress:
      - hostname: stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: stinkyboi.com
          httpHostHeader: stinkyboi.com
      - hostname: octelium.stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: octelium.stinkyboi.com
          httpHostHeader: stinkyboi.com
      - hostname: portal.stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: portal.stinkyboi.com
          httpHostHeader: portal.stinkyboi.com
      - hostname: octelium-api.stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: octelium-api.stinkyboi.com
          httpHostHeader: octelium-api.stinkyboi.com
      - hostname: affine.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: affine.stinkyboi.com
      - hostname: argocd.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: argocd.stinkyboi.com
      - hostname: compass.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: compass.stinkyboi.com
      - hostname: cordium.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: cordium.stinkyboi.com
      - hostname: "*.cordium.stinkyboi.com"
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
      - hostname: console.stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: console.stinkyboi.com
          httpHostHeader: console.stinkyboi.com
      - hostname: deluge.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: deluge.stinkyboi.com
      - hostname: grafana.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: grafana.stinkyboi.com
      - hostname: kiali.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: kiali.stinkyboi.com
      - hostname: litellm.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: litellm.stinkyboi.com
      - hostname: n8n.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: n8n.stinkyboi.com
      - hostname: n8n-webhook.stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: n8n-webhook.stinkyboi.com
          httpHostHeader: n8n-webhook.stinkyboi.com
      - hostname: octobot.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: octobot.stinkyboi.com
      - hostname: openclaw.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: openclaw.stinkyboi.com
      - hostname: policy-bot.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: policy-bot.stinkyboi.com
      - hostname: policy-bot-hook.stinkyboi.com
        service: https://istio-ingressgateway.istio-system.svc.cluster.local:443
        originRequest:
          originServerName: policy-bot-hook.stinkyboi.com
          httpHostHeader: policy-bot-hook.stinkyboi.com
      - hostname: prowlarr.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: prowlarr.stinkyboi.com
      - hostname: radarr.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: radarr.stinkyboi.com
      - hostname: sonarr.stinkyboi.com
        service: http://octelium-ingress-dataplane.octelium.svc.cluster.local:8080
        originRequest:
          httpHostHeader: sonarr.stinkyboi.com
      - service: http_status:404
