---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: octelium-public-cloudflared-credentials
  namespace: octelium-public
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: octelium-public
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: octelium-public-cloudflared-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: cloudflared
          app.kubernetes.io/part-of: octelium-public
  data:
    - secretKey: credentials.json
      remoteRef:
        key: /homelab/octelium/cloudflare-tunnel-credentials-json
