---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: octelium-public
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: octelium-public
automountServiceAccountToken: false
