apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
  annotations:
    homelab.rst.io/runtime-prerequisite: aws-ssm-auth-secret
spec:
  conditions:
    - namespaces:
        - ai
        - argocd
        - automation
        - cert-manager
        - media
        - monitoring
        - octelium-client
        - octelium-storage
        - tailscale
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-auth
            namespace: external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-ssm-auth
            namespace: external-secrets
            key: secret-access-key
