apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-components
  namespace: harbor
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: harbor
      ports:
        # core/portal/nginx, jobservice, registry+controller, trivy, redis.
        - {protocol: TCP, port: 8443}
        - {protocol: TCP, port: 5443}
        - {protocol: TCP, port: 6379}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - {protocol: TCP, port: 8001}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-nginx
  namespace: harbor
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - {protocol: TCP, port: 8443}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-core-bootstrap
  namespace: harbor
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: harbor
              app.kubernetes.io/component: bootstrap
      ports:
        - {protocol: TCP, port: 8443}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: harbor-vulnerability-exporter
  namespace: harbor
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - {protocol: TCP, port: 8080}
        - {protocol: TCP, port: 8081}
