apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshPolicy: Periodic
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: grafana-admin
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: /homelab/grafana/admin-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: /homelab/grafana/admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-azuread-sso
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: grafana-azuread-sso
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: /homelab/grafana/azuread/client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: /homelab/grafana/azuread/client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: auth_url
      remoteRef:
        key: /homelab/grafana/azuread/auth-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: token_url
      remoteRef:
        key: /homelab/grafana/azuread/token-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: allowed_organizations
      remoteRef:
        key: /homelab/grafana/azuread/allowed-organizations
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
