apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: policy-bot-config
  namespace: automation
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: policy-bot-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: policy-bot
          app.kubernetes.io/part-of: homelab-automation
      data:
        policy-bot.yml: |
          server:
            address: "0.0.0.0"
            port: 8080
            public_url: https://policy-bot.stinkyboi.com
          logging:
            text: false
            level: info
          github:
            web_url: "https://github.com"
            v3_api_url: "https://api.github.com"
            v4_api_url: "https://api.github.com/graphql"
            app:
              integration_id: {{ .integration_id }}
              webhook_secret: "{{ .webhook_secret }}"
              private_key: |
                {{ .private_key | replace "\n" "\n      " }}
            oauth:
              client_id: "{{ .oauth_client_id }}"
              client_secret: "{{ .oauth_client_secret }}"
          sessions:
            key: "{{ .sessions_key }}"
          options:
            policy_path: .policy.yml
            shared_repository: .github
            status_check_context: policy-bot
  data:
    - secretKey: integration_id
      remoteRef:
        key: /homelab/policy-bot/github-app/integration-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: webhook_secret
      remoteRef:
        key: /homelab/policy-bot/github-app/webhook-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: private_key
      remoteRef:
        key: /homelab/policy-bot/github-app/private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: oauth_client_id
      remoteRef:
        key: /homelab/policy-bot/oauth/client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: oauth_client_secret
      remoteRef:
        key: /homelab/policy-bot/oauth/client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: sessions_key
      remoteRef:
        key: /homelab/policy-bot/sessions-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
