apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - initdb-configmap.yaml
  - service.yaml
  - statefulset.yaml
  - networkpolicy.yaml
images:
  - name: pgvector/pgvector
    newName: pgvector/pgvector
    newTag: pg16
