apiVersion: v1
kind: Service
metadata:
  name: affine-postgres
  namespace: collaboration
  labels:
    app.kubernetes.io/name: affine-postgres
    app.kubernetes.io/part-of: affine
spec:
  selector:
    app.kubernetes.io/name: affine-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
