apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - harbor-pull-secret.yaml
  - registry-externalsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - authorizationpolicy.yaml
  - virtualservice.yaml
