include "root" {
  path = find_in_parent_folders("root.hcl")
}

include "kubernetes_provider" {
  path = find_in_parent_folders("kubernetes-provider.hcl")
}

terraform {
  source = "../../../modules/argocd-application-kubernetes"
}

dependencies {
  paths = [
    "../octelium-cluster",
    "../octelium-enterprise"
  ]
}

locals {
  repo_url        = "https://github.com/Stuhlmuller/homelab.git"
  target_revision = "main"
}

inputs = {
  metadata = {
    name      = "cordium"
    namespace = "argocd"
    labels = {
      "app.kubernetes.io/managed-by" = "terragrunt"
      "app.kubernetes.io/part-of"    = "homelab"
    }
  }

  project = "homelab"

  destination = {
    server    = "https://kubernetes.default.svc"
    namespace = "octelium"
  }

  sources = [
    {
      repo_url        = local.repo_url
      target_revision = local.target_revision
      path            = "clusters/homelab/apps/cordium"
      kustomize       = {}
    }
  ]

  sync_policy = {
    automated = {
      prune     = false
      self_heal = true
    }
    sync_options = [
      "CreateNamespace=false",
      "ServerSideApply=true"
    ]
    retry = {
      limit = "5"
      backoff = {
        duration     = "30s"
        factor       = "2"
        max_duration = "2m"
      }
    }
  }

  info = [
    {
      name  = "bootstrap"
      value = "Runs cordium-genesis 0.12.7 against the self-hosted Octelium Cluster"
    },
    {
      name  = "access"
      value = "Human browser access and agent API access are separate Octelium identities and Services"
    },
    {
      name  = "state"
      value = "Cordium runtime resources are generated by upstream genesis and Octelium controllers"
    }
  ]
}
