apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-postgres-auth
  namespace: media
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: media-postgres-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        POSTGRES_USER: media_apps
        POSTGRES_DB: media_apps
        POSTGRES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /homelab/media-postgres/app-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-postgres-arr-env
  namespace: media
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: media-postgres-arr-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        SONARR_POSTGRES_HOST: media-postgres.media.svc.cluster.local
        SONARR_POSTGRES_PORT: "5432"
        SONARR_POSTGRES_USER: media_apps
        SONARR_POSTGRES_PASSWORD: "{{ .password }}"
        SONARR_POSTGRES_MAIN_DB: sonarr-main
        SONARR_POSTGRES_LOG_DB: sonarr-log
        RADARR_POSTGRES_HOST: media-postgres.media.svc.cluster.local
        RADARR_POSTGRES_PORT: "5432"
        RADARR_POSTGRES_USER: media_apps
        RADARR_POSTGRES_PASSWORD: "{{ .password }}"
        RADARR_POSTGRES_MAIN_DB: radarr-main
        RADARR_POSTGRES_LOG_DB: radarr-log
        PROWLARR_POSTGRES_HOST: media-postgres.media.svc.cluster.local
        PROWLARR_POSTGRES_PORT: "5432"
        PROWLARR_POSTGRES_USER: media_apps
        PROWLARR_POSTGRES_PASSWORD: "{{ .password }}"
        PROWLARR_POSTGRES_MAIN_DB: prowlarr-main
        PROWLARR_POSTGRES_LOG_DB: prowlarr-log
  data:
    - secretKey: password
      remoteRef:
        key: /homelab/media-postgres/app-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
