apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-cronjob.yaml
  - externalsecret.yaml
  - initdb-configmap.yaml
  - local-storage.yaml
  - networkpolicy.yaml
  - service.yaml
  - statefulset.yaml
