apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: media-postgres
  namespace: media
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: media-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: media
      ports:
        - protocol: TCP
          port: 5432
