apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: media
  labels:
    app.kubernetes.io/instance: deluge
    app.kubernetes.io/name: deluge
    app.kubernetes.io/service: deluge
    homelab.rst.io/cross-namespace-alias: deluge
spec:
  type: ExternalName
  externalName: deluge.deluge.svc.cluster.local
  ports:
    - name: http
      port: 8112
      protocol: TCP
      targetPort: 8112
