metrics:
  enabled: true

debug:
  enabled: false

onlyViewOnlyMode: true
allowAdHocKialiNamespace: false
allowAdHocKialiImage: false
allowAdHocOSSMConsoleImage: false
allowAdHocContainers: false
allowSecurityContextOverride: false

image:
  digest: sha256
  tag: ca2e4c356e946849883f42e9c9fe41080145cb442f93200cfca4e55a89a62039
env:
  - name: RELATED_IMAGE_kiali_default
    value: quay.io/kiali/kiali:v2.26.0@sha256:59cce98a9811ce53ff3da771225d1df00f0ca4ae0819311291ae7316349a13e9

cr:
  create: true
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  spec:
    istio_namespace: istio-system
    auth:
      strategy: anonymous
    deployment:
      namespace: monitoring
      cluster_wide_access: true
      service_type: ClusterIP
      view_only_mode: true
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 512Mi
    external_services:
      grafana:
        enabled: true
        external_url: https://grafana.stinkyboi.com
        internal_url: http://grafana.monitoring.svc.cluster.local
      prometheus:
        enabled: true
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    server:
      web_fqdn: kiali.stinkyboi.com
      web_port: "443"
      web_root: /
      web_schema: https
