apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali-tailnet
  namespace: monitoring
  annotations:
    homelab.rst.io/public-funnel: "false"
spec:
  hosts:
    - kiali.stinkyboi.com
  gateways:
    - istio-system/tailnet-gateway
  http:
    - route:
        - destination:
            host: kiali.monitoring.svc.cluster.local
            port:
              number: 20001
