kind: Deployment
image:
  tag: v0.33.0@sha256:de38c88dcb1e7d822c4bd320551cc55e541c160c6ba380d99772949b0c967ab0
deschedulerPolicy:
  profiles:
    - name: conservative
      pluginConfig:
        - name: DefaultEvictor
          args:
            evictSystemCriticalPods: false
            ignorePvcPods: true
            minReplicas: 2
      plugins:
        balance:
          enabled:
            - LowNodeUtilization
        deschedule:
          enabled:
            - RemovePodsViolatingInterPodAntiAffinity
schedule: "*/30 * * * *"
