apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet
  namespace: fleet
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-datastores
  namespace: fleet
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-bootstrap
  namespace: fleet
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-backup
  namespace: fleet
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
