apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: wazuh-selfsigned
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-ca
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  secretName: wazuh-ca
  commonName: wazuh-ca
  isCA: true
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 3072
    encoding: PKCS8
    rotationPolicy: Never
  usages: [digital signature, cert sign, crl sign]
  issuerRef:
    name: wazuh-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: wazuh-ca
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  ca:
    secretName: wazuh-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-indexer-tls
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: wazuh-indexer-tls
  commonName: wazuh-indexer
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - wazuh-indexer
    - wazuh-indexer.wazuh
    - wazuh-indexer.wazuh.svc
    - wazuh-indexer.wazuh.svc.cluster.local
    - wazuh-indexer-0.wazuh-indexer.wazuh.svc.cluster.local
    - localhost
  ipAddresses: [127.0.0.1]
  privateKey:
    algorithm: RSA
    size: 3072
    encoding: PKCS8
    rotationPolicy: Always
  usages: [server auth, client auth]
  issuerRef:
    name: wazuh-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-manager-tls
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: wazuh-manager-tls
  commonName: wazuh-manager
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - wazuh-manager
    - wazuh-manager.wazuh
    - wazuh-manager.wazuh.svc
    - wazuh-manager.wazuh.svc.cluster.local
    - localhost
  ipAddresses: [127.0.0.1]
  privateKey:
    algorithm: RSA
    size: 3072
    encoding: PKCS8
    rotationPolicy: Always
  usages: [server auth, client auth]
  issuerRef:
    name: wazuh-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-admin-tls
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: wazuh-admin-tls
  commonName: wazuh-admin
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 3072
    encoding: PKCS8
    rotationPolicy: Always
  usages: [client auth]
  issuerRef:
    name: wazuh-ca
    kind: Issuer
