apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-local
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-indexer-local
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/part-of: wazuh
    homelab.stuhlmuller.dev/storage-backend: talos-ephemeral-local
spec:
  accessModes: [ReadWriteOnce]
  capacity: {storage: 100Gi}
  claimRef: {name: wazuh-indexer-local, namespace: wazuh}
  hostPath:
    path: /var/lib/wazuh-indexer
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [acer]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wazuh-local
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-local
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: {storage: 100Gi}
  storageClassName: wazuh-local
  volumeMode: Filesystem
  volumeName: wazuh-indexer-local
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-local
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/part-of: wazuh
    homelab.stuhlmuller.dev/storage-backend: talos-ephemeral-local
spec:
  accessModes: [ReadWriteOnce]
  capacity: {storage: 50Gi}
  claimRef: {name: wazuh-manager-local, namespace: wazuh}
  hostPath:
    path: /var/lib/wazuh-manager
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [acer]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wazuh-local
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-local
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: {storage: 50Gi}
  storageClassName: wazuh-local
  volumeMode: Filesystem
  volumeName: wazuh-manager-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-backups
  namespace: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests: {storage: 150Gi}
  storageClassName: nfs-default
