apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: wazuh-octelium
  namespace: wazuh
  annotations:
    homelab.rst.io/access-plane: octelium
    homelab.rst.io/public-funnel: "false"
spec:
  hosts: [wazuh.stinkyboi.com]
  gateways: [istio-system/tailnet-gateway]
  http:
    - route:
        - destination:
            host: wazuh-dashboard.wazuh.svc.cluster.local
            port:
              number: 5601
