apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tines-secrets
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: tines-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: /homelab/tines/app-secret
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /homelab/tines/admin-password

