apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tines-secrets
  namespace: automation
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: tines-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: /homelab/tines/app-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /homelab/tines/admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
