apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tines-registry
  namespace: automation
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: tines-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .configJson }}"
  data:
    - secretKey: configJson
      remoteRef:
        key: /homelab/tines/registry-dockerconfigjson
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
