apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finance
resources:
  - externalsecret.yaml
  - virtualservice.yaml
configMapGenerator:
  - name: freqtrade-config
    files:
      - config.json=config.json
    options:
      labels:
        app.kubernetes.io/name: freqtrade
        app.kubernetes.io/part-of: homelab
  - name: freqtrade-strategies
    files:
      - HomelabBtcTrend.py=strategies/HomelabBtcTrend.py
    options:
      labels:
        app.kubernetes.io/name: freqtrade
        app.kubernetes.io/part-of: homelab
generatorOptions:
  disableNameSuffixHash: true
