apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: octelium-ingress-dataplane
  namespace: octelium
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: octelium-ingress-dataplane
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: octelium-ingress-dataplane
  namespace: octelium
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: octelium
      octelium.com/component: ingress-dataplane
      octelium.com/component-type: cluster
