apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: octelium-cluster
  namespace: istio-system
  annotations:
    homelab.rst.io/public-funnel: "false"
spec:
  hosts:
    - octelium.stinkyboi.com
    - portal.octelium.stinkyboi.com
    - octelium-api.octelium.stinkyboi.com
  gateways:
    - istio-system/tailnet-gateway
  http:
    - route:
        - destination:
            host: octelium-ingress-dataplane.octelium.svc.cluster.local
            port:
              number: 443
