image:
  repository: ghcr.io/berriai/litellm-database
  tag: v1.96.2@sha256:80e5e92bdcca246cd4153d451e5f75b65e19c7e39c46cc88a38bed4b65cc5836
serviceAccount:
  create: true
  automount: false
  name: litellm
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
environmentSecrets:
  - litellm-provider-keys
service:
  type: ClusterIP
  port: 4000
masterkeySecretName: litellm-provider-keys
masterkeySecretKey: LITELLM_MASTER_KEY
proxy_config:
  general_settings:
    master_key: os.environ/LITELLM_MASTER_KEY
  model_list:
    - model_name: openai-default
      litellm_params:
        model: openai/gpt-4.1-mini
        api_key: os.environ/OPENAI_API_KEY
db:
  deployStandalone: false
migrationJob:
  enabled: false
