image:
  repository: ghcr.io/berriai/litellm-database
  tag: ""
environmentSecrets:
  - litellm-provider-keys
service:
  type: ClusterIP
  port: 4000
masterkeySecretName: litellm-provider-keys
masterkeySecretKey: LITELLM_MASTER_KEY
proxy_config:
  general_settings:
    master_key: os.environ/LITELLM_MASTER_KEY
  model_list:
    - model_name: openai-default
      litellm_params:
        model: openai/gpt-4.1-mini
        api_key: os.environ/OPENAI_API_KEY
db:
  deployStandalone: false
migrationJob:
  enabled: false
