image:
  repository: ghcr.io/berriai/litellm-database
  tag: "@sha256:cdb39b2c0010140763c2ea6b57b7b6b4131c4cfa4984c0b969f7025563d167ef"
environmentSecrets:
  - litellm-provider-keys
service:
  type: ClusterIP
  port: 4000
masterkeySecretName: litellm-provider-keys
masterkeySecretKey: LITELLM_MASTER_KEY
proxy_config:
  general_settings:
    master_key: os.environ/LITELLM_MASTER_KEY
  model_list:
    - model_name: openai-default
      litellm_params:
        model: openai/gpt-4.1-mini
        api_key: os.environ/OPENAI_API_KEY
db:
  deployStandalone: false
migrationJob:
  enabled: false
