apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - backup-pvc.yaml
  - postgres.yaml
  - redis.yaml
  - networkpolicy.yaml
  - backup-cronjob.yaml
  - restore-drill-cronjob.yaml
configMapGenerator:
  - name: octelium-postgres-restore-drill
    namespace: octelium-storage
    files:
      - restore-drill.sh
