all:
  children:
    nomad_servers:
      hosts:
        acer:
          ansible_host: 10.1.0.199
          tailscale_ip: 100.119.126.81
          consul_node_name: consul-primary
          nomad_node_name: nomad-primary
          nomad_node_class: ingress
          tailscale_funnel_https_port: 8443
          tailscale_funnel_mounts:
            - path: /
              target: http://127.0.0.1:18080
        zimaboard-0:
          ansible_host: 10.1.0.200
          tailscale_ip: 100.94.104.7
          consul_node_name: consul-0
          nomad_node_name: nomad-0
          nomad_node_class: worker
          tailscale_advertise_routes:
            - 10.1.0.0/24
        zimaboard-1:
          ansible_host: 10.1.0.201
          tailscale_ip: 100.102.247.126
          consul_node_name: consul-1
          nomad_node_name: nomad-1
          nomad_node_class: worker
        zimaboard-2:
          ansible_host: 10.1.0.202
          tailscale_ip: 100.78.60.65
          consul_node_name: consul-2
          nomad_node_name: nomad-2
          nomad_node_class: worker
