apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge-auth
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: deluge-auth
    creationPolicy: Owner
  data:
    - secretKey: web-password
      remoteRef:
        key: /homelab/deluge/web-password

