apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge-vpn
  namespace: media
  annotations:
    homelab.rst.io/wireguard-profile-ssm-version: "2"
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: deluge-vpn
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        wg0.conf: |
          [Interface]
          PrivateKey = {{ .WIREGUARD_PRIVATE_KEY }}
          Address = {{ regexFind "[0-9.]+/[0-9]+" .WIREGUARD_ADDRESSES }}

          [Peer]
          PublicKey = {{ .WIREGUARD_PUBLIC_KEY }}
          PresharedKey = {{ .WIREGUARD_PRESHARED_KEY }}
          Endpoint = {{ .WIREGUARD_ENDPOINT_IP }}:{{ .WIREGUARD_ENDPOINT_PORT }}
          AllowedIPs = 0.0.0.0/0
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-preshared-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-public-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-addresses
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-endpoint-ip
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_ENDPOINT_PORT
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-endpoint-port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
