apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge-vpn
  namespace: media
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: deluge-vpn
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-preshared-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: /homelab/deluge/vpn/wireguard-addresses
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
