apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: deluge-strict-mtls
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: deluge
      app.kubernetes.io/name: deluge
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deluge-allow-media-clients
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: deluge
      app.kubernetes.io/name: deluge
  action: ALLOW
  rules:
    - from:
        - source:
            serviceAccounts:
              - radarr
              - sonarr
              - prowlarr
      to:
        - operation:
            ports:
              - "8112"
