controllers:
  deluge:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/deluge
          tag: 2.1.1@sha256:9de4b097e0cb5dceb5ef0aaa4deb2565101c65e7d06770a59151770750a54858
        env:
          TZ: America/Los_Angeles
          PUID: "1000"
          PGID: "1000"
service:
  app:
    controller: deluge
    ports:
      http:
        port: 8112
      bittorrent:
        port: 6881
persistence:
  config:
    enabled: true
    storageClass: nfs-default
    size: 5Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
  downloads:
    enabled: true
    storageClass: nfs-default
    size: 200Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /downloads

