global:
  logging:
    level: default:info
pilot:
  replicaCount: 1
meshConfig:
  accessLogFile: /dev/stdout
service:
  annotations:
    homelab.rst.io/pod-security: tailscale-proxy-requires-privileged
    tailscale.com/hostname: homelab-istio
  loadBalancerClass: tailscale
gateways:
  istio-ingressgateway:
    enabled: true
