profile: ambient
cni:
  ambient:
    dnsCapture: false
    ipv6: false
  podAnnotations:
    homelab.rst.io/ambient-ip-family: ipv4
global:
  logging:
    level: default:info
pilot:
  replicaCount: 1
meshConfig:
  accessLogFile: /dev/stdout
service:
  type: ClusterIP
gateways:
  istio-ingressgateway:
    enabled: true
