profile: ambient
cni:
  ambient:
    dnsCapture: false
global:
  logging:
    level: default:info
pilot:
  replicaCount: 1
meshConfig:
  accessLogFile: /dev/stdout
service:
  type: ClusterIP
gateways:
  istio-ingressgateway:
    enabled: true
