apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres-auth
  namespace: automation
  annotations:
    homelab.stuhlmuller.dev/generated-secret-revision: "v1"
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: n8n-postgres-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ .admin_password }}"
        POSTGRES_APP_PASSWORD: "{{ .app_password }}"
  data:
    - secretKey: admin_password
      remoteRef:
        key: /homelab/n8n/postgres-admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: app_password
      remoteRef:
        key: /homelab/n8n/postgres-app-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres-client
  namespace: automation
  annotations:
    homelab.stuhlmuller.dev/generated-secret-revision: "v1"
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: n8n-postgres-client
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        DB_POSTGRESDB_PASSWORD: "{{ .app_password }}"
  data:
    - secretKey: app_password
      remoteRef:
        key: /homelab/n8n/postgres-app-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
