apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-n8n-postgres-0
  namespace: automation
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: n8n-postgres
    app.kubernetes.io/part-of: homelab-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-default
  resources:
    requests:
      storage: 20Gi
