apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hummingbot-conf
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/instance: hummingbot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hummingbot
    helm.sh/chart: app-template-4.4.0
    homelab.rst.io/retired: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-default
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hummingbot-logs
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/instance: hummingbot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hummingbot
    helm.sh/chart: app-template-4.4.0
    homelab.rst.io/retired: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-default
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hummingbot-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/instance: hummingbot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hummingbot
    helm.sh/chart: app-template-4.4.0
    homelab.rst.io/retired: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-default
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hummingbot-certs
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/instance: hummingbot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hummingbot
    helm.sh/chart: app-template-4.4.0
    homelab.rst.io/retired: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-default
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hummingbot-scripts
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/instance: hummingbot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hummingbot
    helm.sh/chart: app-template-4.4.0
    homelab.rst.io/retired: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-default
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hummingbot-controllers
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/instance: hummingbot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hummingbot
    helm.sh/chart: app-template-4.4.0
    homelab.rst.io/retired: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-default
  volumeMode: Filesystem
