apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hummingbot-tailnet
  namespace: finance
  annotations:
    homelab.rst.io/public-funnel: "false"
spec:
  hosts:
    - hummingbot.stinkyboi.com
  gateways:
    - istio-system/tailnet-gateway
  http:
    - route:
        - destination:
            host: hummingbot.finance.svc.cluster.local
            port:
              number: 8000
