name: 'Setup Infrastructure'
description: 'Common setup for Terragrunt workflows - AWS, Tailscale, and kubeconfig'

inputs:
  aws-role-arn:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-west-2'
  tailscale-auth-key:
    description: 'Tailscale auth key'
    required: true
  kube-config:
    description: 'Kubeconfig content'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: github-actions-session

    - name: Tailscale
      uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4
      with:
        authkey: ${{ inputs.tailscale-auth-key }}
        tags: tag:ci
        statedir: /tmp/tailscale-state/

    - name: Setup kubeconfig
      shell: bash
      run: |
        mkdir -p $HOME/.kube
        echo "${{ inputs.kube-config }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
