locals {
  shared = read_terragrunt_config(find_in_parent_folders("stack-defaults.hcl")).locals
}

inputs = {
  defaults     = local.shared.argocd_defaults
  dependencies = ["external-secrets", "octelium-cluster", "octelium-enterprise", "platform-storage"]
  spec = {
    destination = {
      namespace = "octelium"
    }
    syncPolicy = {
      syncOptions = ["CreateNamespace=false", "ServerSideApply=true"]
    }
    info = [
      {
        name  = "bootstrap"
        value = "Runs cordium-genesis 0.12.7 against the self-hosted Octelium Cluster"
      },
      {
        name  = "access"
        value = "Human browser access and agent API access are separate Octelium identities and Services"
      },
      {
        name  = "state"
        value = "Cordium runtime resources are generated by upstream genesis and Octelium controllers"
      }
    ]
  }
}
