apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - externalsecret.yaml
  - token-certificate.yaml
  - local-storage.yaml
  - pvc.yaml
  - postgres.yaml
  - backup-cronjob.yaml
  - backup-job.yaml
  - networkpolicy.yaml
  - virtualservice.yaml
  - bootstrap-job.yaml
configMapGenerator:
  - name: harbor-bootstrap
    namespace: harbor
    files:
      - bootstrap.py
  - name: harbor-backup
    namespace: harbor
    files:
      - backup.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
