apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - certificate.yaml
  - networkpolicy.yaml
  - authorizationpolicy.yaml
  - funnel.yaml
configMapGenerator:
  - name: traefik-routes
    files:
      - routes.yaml
      - tls.yaml
generatorOptions:
  disableNameSuffixHash: true
