apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traefik
  namespace: traefik
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tailscale
      ports:
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 8443}
        - {protocol: TCP, port: 8080}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: harbor
          podSelector:
            matchLabels:
              app.kubernetes.io/name: harbor-image-signing
      ports:
        - {protocol: TCP, port: 8443}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: octelium
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cordium
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: [genesis, cluster-config]
      ports:
        - {protocol: TCP, port: 8443}
    - ports:
        - {protocol: TCP, port: 15008}
    - from:
        - ipBlock: {cidr: 10.1.0.199/32}
        - ipBlock: {cidr: 10.1.0.200/32}
        - ipBlock: {cidr: 10.1.0.201/32}
        - ipBlock: {cidr: 10.1.0.202/32}
      ports:
        - {protocol: TCP, port: 9443}
    - from:
        - ipBlock: {cidr: 169.254.7.127/32}
      ports:
        - {protocol: TCP, port: 9000}
