apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authorizationpolicy.yaml
  - networkpolicy.yaml
  - namespace.yaml
  - externalsecret.yaml
  - datastores.yaml
  - virtualservice.yaml
  - recovery-pvc.yaml
configMapGenerator:
  - name: langfuse-clickhouse-logging
    namespace: langfuse
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    files:
      - 90-homelab-logging.xml=clickhouse-logging.xml
