apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ../n8n-postgres-cold
  - readers.yaml
configMapGenerator:
  - name: n8n-checkpoint-reader
    files:
      - read.sh
