apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-exit-node
  annotations:
    homelab.rst.io/pod-security: tailscale-proxy-requires-privileged
  labels:
    app.kubernetes.io/name: homelab-exit-node
    app.kubernetes.io/part-of: tailscale
    homelab.stuhlmuller.dev/role: exit-node
spec:
  hostname: homelab-exit-node
  tags:
    - tag:k8s
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - 10.1.0.0/24
