apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: operator-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: /homelab/tailscale/oauth-client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: client_secret
      remoteRef:
        key: /homelab/tailscale/oauth-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
