---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-sso
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-oidc-sso
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: argocd
    homelab.stuhlmuller.dev/cluster: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: argocd-oidc-sso
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: argocd-oidc-sso
          app.kubernetes.io/part-of: argocd
          app.kubernetes.io/managed-by: external-secrets
  data:
    - secretKey: url
      remoteRef:
        key: /homelab/argocd/oidc/url
    - secretKey: issuer
      remoteRef:
        key: /homelab/argocd/oidc/issuer
    - secretKey: clientID
      remoteRef:
        key: /homelab/argocd/oidc/client-id
    - secretKey: clientSecret
      remoteRef:
        key: /homelab/argocd/oidc/client-secret
