apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-tailnet
  namespace: argocd
  annotations:
    homelab.rst.io/public-funnel: "false"
spec:
  hosts:
    - argocd.stinkyboi.com
  gateways:
    - istio-system/tailnet-gateway
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
