apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - backup-cronjob.yaml
  - backup-job.yaml
  - backup-pvc.yaml
  - local-storage.yaml
  - networkpolicy.yaml
  - reconcile-job.yaml
configMapGenerator:
  - name: bazarr-bootstrap
    files:
      - bootstrap.py
      - profile.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
