
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git::https://github.com/Stuhlmuller/terragrunt-catalog.git//modules/nomad-job?ref=0.2.0"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Inline jobspec content (HCL or JSON)
  # Type: string
  # jobspec_content = null

  # Description: Path to jobspec file
  # Type: string
  jobspec_file = "${dirname(find_in_parent_folders("root.hcl"))}/jobs/traefik.nomad.hcl"

  # Description: Whether the jobspec is in JSON format
  # Type: bool
  # json_format = false

  # Description: Deregister job when resource is destroyed
  # Type: bool
  # deregister_on_destroy = true

  # Description: Purge job when resource is destroyed
  # Type: bool
  # purge_on_destroy = false

  # Description: Deregister job if the ID changes
  # Type: bool
  # deregister_on_id_change = true

  # Description: Force job to run again if status is dead
  # Type: bool
  # rerun_if_dead = false

  # Description: Return immediately after creating/updating
  # Type: bool
  # detach = true

  # Description: Override soft-mandatory Sentinel policies
  # Type: bool
  # policy_override = false

  # Description: Enable HCL2 parser options
  # Type: bool
  # hcl2_enabled = false

  # Description: Allow HCL2 filesystem functions
  # Type: bool
  # hcl2_allow_fs = false

  # Description: Variables to pass to HCL2 parser (all values must be strings)
  # Type: map
  # hcl2_vars = {}

  # Description: Timeout configuration for job operations
  # Type: object
  # timeouts = null

}
