---
name: Lint
on:
  pull_request:
permissions: {}
concurrency:
  group: super-linter-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout code
        uses: chainguard-actions/actions-checkout@279383ec3b8d70f964ffa5a2151ea3d2a5317ec6 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Super-Linter
        uses: chainguard-actions/super-linter-super-linter@bf49e660c836f9c76777ae48293f937565e314d7 # v8.7.0
        env:
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAGRUNT: true
          VALIDATE_YAML: true
