name: "Release"

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release-dry-run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: chainguard-actions/actions-checkout@279383ec3b8d70f964ffa5a2151ea3d2a5317ec6 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release Dry Run
        uses: chainguard-actions/cycjimmy-semantic-release-action@b4e37369e853084a108f15ea5f1a9fc0cfe757ef # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          ci: false

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating releases
    steps:
      - name: Checkout code
        uses: chainguard-actions/actions-checkout@279383ec3b8d70f964ffa5a2151ea3d2a5317ec6 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: chainguard-actions/cycjimmy-semantic-release-action@b4e37369e853084a108f15ea5f1a9fc0cfe757ef # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: false
          ci: true
