apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: prometheus-allow-grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/monitoring/sa/grafana
              - cluster.local/ns/monitoring/sa/kiali-service-account
              - cluster.local/ns/monitoring/sa/prometheus-kube-prometheus-prometheus
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: alertmanager-allow-monitoring-clients
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      alertmanager: prometheus-kube-prometheus-alertmanager
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/monitoring/sa/grafana
              - cluster.local/ns/monitoring/sa/prometheus-kube-prometheus-alertmanager
              - cluster.local/ns/monitoring/sa/prometheus-kube-prometheus-prometheus
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kube-state-metrics-allow-prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: prometheus
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/monitoring/sa/prometheus-kube-prometheus-prometheus
