grafana:
  enabled: false
nodeExporter:
  enabled: false
defaultRules:
  rules:
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
  disabled:
    Watchdog: true
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: monitoring
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
