---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cordium-local-path-provisioner-application.yaml
  - nfs-subdir-external-provisioner-application.yaml
